# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf6e4037ed64be61aac72a29095ed9814c12d9799a7ad12af39a64b91b80afaf16142c20fca6f48bcaf05c9e1c6813653ab4a620e10ddf2da031c16242664c3a

test:
  secret_key_base: 9fb507a1190667c38b8a4502366b2cc0c4c50f90bb6e04bcedfeafe12f78bf125c09bf9e26f722af958a9ad2bf27ced20d0f2caea3313f23bb0178c15b826698

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
